export * from "@/generate/request/add-movie-request.ts";
export * from "@/generate/request/login-request.ts";
export * from "@/generate/request/logout-request.ts";
export * from "@/generate/request/register-request.ts";
export * from "@/generate/request/search-movie-info-request.ts";
export * from "@/generate/request/search-movie-type-request.ts";
export * from "@/generate/request/search-user-request.ts";
export * from "@/generate/request/update-movie-info-request.ts";
export * from "@/generate/request/update-user-info-request.ts";
